services:
  backend:
    build: ./backend
    container_name: dms-backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=:8080
      - ALLOW_ORIGINS=http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000,http://127.0.0.1:8080,http://dms-frontend:3000,http://172.18.0.3:3000
      - UPLOAD_DIR=/app/uploads
      - LOG_DIR=/app/logs
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - dms-network

  frontend:
    build:
      context: ./fontend
    container_name: dms-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://dms-backend:8080
    restart: unless-stopped
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
